---
generate:
  show: true
  input_info:
    input_type: actionButton
    input_params:
      inputId: generate_img
      label: Generate
  update_param: value
width:
  show: true
  input_info:
    input_type: sliderInput
    input_params:
      inputId: width_img
      label: Width
      min: 0
      max: 300
      value: 40
      step: 1
  update_param: value
height:
  show: true
  input_info:
    input_type: sliderInput
    input_params:
      inputId: height_img
      label: Height
      min: 0
      max: 300
      value: 40
      step: 1
  update_param: value
brightness:
  show: true
  input_info:
    input_type: sliderInput
    input_params:
      inputId: brightness_img
      label: Brightness
      min: 0
      max: 10
      value: 1
      step: 0.1
  update_param: value
contrast:
  show: true
  child_info:
    depends_on: color_palette
    other: false
    filter:
      - bw
  input_info:
    input_type: sliderInput
    input_params:
      inputId: contrast_img
      label: Contrast
      min: 0
      max: 20
      value: 1
      step: 0.1
  update_param: value
method:
  show: true
  input_info:
    input_type: selectizeInput
    input_params:
      inputId: method_img
      label: Method
      choices:
        Clasic:
        - brickr_classic
        Euclidean:
        - euclidean
        CIE 1976:
        - cie1976
        CIE 94:
        - cie94
        CIE 2000:
        - cie2000
        CMC:
        - cmc
      selected: brickr_classic
  update_param: selected
dithering:
  show: true
  input_info:
    input_type: checkboxInput
    input_params:
      inputId: dithering_img
      label: Dithering
      value: false
  update_param: value
color_palette:
  show: true
  input_info:
    input_type: radioButtons
    input_params:
      inputId: color_palette_img
      label: Color palette
      choices:
        Universal:
        - universal
        Generic:
        - generic
        Special:
        - special
        Grayscale:
        - bw
      inline: true
  update_param: select
#color_table:
#  show: true
#  input_info:
#    input_type: colourInput
#    input_params:
#      inputId: color_table_img
#      label: Colors
#      value: "#000000"
#  update_param: value
nDigits:
  show: true
  input_info:
    input_type: numericInput
    input_params:
      inputId: nDigits_viz
      label: Number digits
      value: 2
      min: 1
      max: 13
  update_param: value
